### ISSUE TITLE
Plan del proyecto

### ISSUE THREAD

**Issue by jonas1ara** [Jonas-Lara/IPN-CS#3]
# Plan del proyecto

Desde el año pasado he estado trabajando en la elaboración de este proyecto, que empezó con la idea de ser un tutorial básico del lenguaje C, para los estudiantes menos familiarizados, pero hoy es mucho más que eso y tengo un plan para llevarlo acabo. 

Mi objetivo es terminar de ejecutar este plan a principios de Julio del año 2023 ... 

## Retroalimentación

¡Me encantaría recibir comentarios sobre el plan y si tiene alguna sugerencia!

Puede dejar sus comentarios directamente sobre este issue.

## El plan

Las principales etapas del plan son:

**1. Fundamentos, temas del 1 al 8.**
**2. Algoritmos y estructuras de datos, temas del 9 al 12.**
3. Temas avanzados, temas del 13 al 16.

## Etapa 1: Completar los temas fundamentales para comprender la programación 😛😅

En esta etapa del proyecto quedan pocas cosas que terminar de la etapa 1, pero si las hay:

**1. Básicos del lenguaje C 💩 (Completado)**

2. Matemáticas básicas √ **(En proceso)**

**3. Memoria dinámica 🤯 (Completado)**

4. Hilos en lenguaje C 🧵 **(Sección archivada)**

**5. HowTo 🔧 (Completado)**

6. Algoritmos del Dr. Esaú del curso de fundamentos de programación en el IPN 🎒 **(En proceso)**

**7. Make 🤓  (Completado)**

**8. Consola 💻 (Completado)**

## Etapa 2: Algoritmos y estructuras de datos 💪

**9. Recursión 🤯 (Completado)**

10. Algoritmos 👑  **(En proceso)**

11. Estructuras de datos □ → □ → □ → □  **(En proceso)**

12. Algoritmos del Dr. Esaú del curso de algoritmo y estructuras de datos en el IPN  🎒 **(En proceso)**

## Etapa 3: Temas avanzados 🎓

13. Redes en lenguaje C 🖧 **(Sección archivada)**

14. Métodos numéricos, son ejercicios obtenidos del libro "Análisis numérico de Richard Burden" ⅀

15. GTK, con amor para el escritorio GNOME 👣 **(Sección archivada)**

16. Llamadas al sistema 

17. Es una sección que reúne los 25 algoritmos que a mi parecer todo ingeniero y/o matemático como mínimo debería conocer 👀, comprender ya es avaricia. 😂

Esto es el plan para completar este repositorio, ojalá logre completarlo. 

## Expresiones de gratitud

Escrito con ❤️ por [Jonas Lara](https://www.linkedin.com/in/jonas1ara/) estudiante de ingeniería en IA en la [UPIIT](https://www.upiit.ipn.mx/)

**Comment by Jonas-Lara** [comment]
Trabajo terminado, orgulloso de mi.
